name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    name: Build & Release
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Make build script executable
        run: chmod +x ./build.sh

      - name: Build infra binary
        run: ./build.sh

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: infra
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
